CREATE TABLE hvbp_person_and_community_engagement (
    submission_year INT,
    fiscal_year INT,
    facility_id INT,
    facility_name TEXT,
    address TEXT,
    city_town TEXT,
    state CHAR(2),
    zip_code CHAR(5),
    county_parish TEXT,

    communication_with_nurses_floor REAL,
    communication_with_nurses_achievement_threshold REAL,
    communication_with_nurses_benchmark REAL,
    communication_with_nurses_baseline_rate REAL,
    communication_with_nurses_performance_rate REAL,
    communication_with_nurses_achievement_points TEXT,
    communication_with_nurses_improvement_points TEXT,
    communication_with_nurses_dimension_score REAL,

    communication_with_doctors_floor REAL,
    communication_with_doctors_achievement_threshold REAL,
    communication_with_doctors_benchmark REAL,
    communication_with_doctors_baseline_rate REAL,
    communication_with_doctors_performance_rate REAL,
    communication_with_doctors_achievement_points TEXT,
    communication_with_doctors_improvement_points TEXT,
    communication_with_doctors_dimension_score REAL,

    responsiveness_of_hospital_staff_floor REAL,
    responsiveness_of_hospital_staff_achievement_threshold REAL,
    responsiveness_of_hospital_staff_benchmark REAL,
    responsiveness_of_hospital_staff_baseline_rate REAL,
    responsiveness_of_hospital_staff_performance_rate REAL,
    responsiveness_of_hospital_staff_achievement_points TEXT,
    responsiveness_of_hospital_staff_improvement_points TEXT,
    responsiveness_of_hospital_staff_dimension_score REAL,

    care_transition_floor REAL,
    care_transition_achievement_threshold REAL,
    care_transition_benchmark REAL,
    care_transition_baseline_rate REAL,
    care_transition_performance_rate REAL,
    care_transition_achievement_points TEXT,
    care_transition_improvement_points TEXT,
    care_transition_dimension_score REAL,

    communication_about_medicines_floor REAL,
    communication_about_medicines_achievement_threshold REAL,
    communication_about_medicines_benchmark REAL,
    communication_about_medicines_baseline_rate REAL,
    communication_about_medicines_performance_rate REAL,
    communication_about_medicines_achievement_points TEXT,
    communication_about_medicines_improvement_points TEXT,
    communication_about_medicines_dimension_score REAL,

    cleanliness_and_quietness_floor REAL,
    cleanliness_and_quietness_achievement_threshold REAL,
    cleanliness_and_quietness_benchmark REAL,
    cleanliness_and_quietness_baseline_rate REAL,
    cleanliness_and_quietness_performance_rate REAL,
    cleanliness_and_quietness_achievement_points TEXT,
    cleanliness_and_quietness_improvement_points TEXT,
    cleanliness_and_quietness_dimension_score REAL,

    discharge_information_floor REAL,
    discharge_information_achievement_threshold REAL,
    discharge_information_benchmark REAL,
    discharge_information_baseline_rate REAL,
    discharge_information_performance_rate REAL,
    discharge_information_achievement_points TEXT,
    discharge_information_improvement_points TEXT,
    discharge_information_dimension_score REAL,

    overall_rating_of_hospital_floor REAL,
    overall_rating_of_hospital_achievement_threshold REAL,
    overall_rating_of_hospital_benchmark REAL,
    overall_rating_of_hospital_baseline_rate REAL,
    overall_rating_of_hospital_performance_rate REAL,
    overall_rating_of_hospital_achievement_points TEXT,
    overall_rating_of_hospital_improvement_points TEXT,
    overall_rating_of_hospital_dimension_score REAL,

    hcahps_base_score REAL,
    hcahps_consistency_score REAL
);
